--- #YAML:1.0
name:               Socialtext-Wikrad
version:            0.07
abstract:           efficient wiki browsing and editing
author:
    - Luke Closs <cpan@5thplane.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Curses::UI:           0.95
    JSON:                 0
    Socialtext::EditPage:  0.04
    Socialtext::Resting:  0.24
    Socialtext::Resting::Getopt:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
